# Generated by Django 2.1.3 on 2018-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('detalle', models.TextField(null=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
    ]
